---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: install ssmtp
  package:
    name: "{{ ssmtp_package }}"
    state: present
  environment: "{{ proxy_env }}"
  become: true
  tags: ssmtp

- name: configure /etc/ssmtp/ssmtp.conf & /etc/ssmtp/revaliases
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: ssmtp.config.j2, dest: /etc/ssmtp/ssmtp.conf }
    - { src: ssmtp.revaliases.j2, dest: /etc/ssmtp/revaliases }
  become: true
  tags: ssmtp
